#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = 
CFLAGS = -Wall `wx-config  --cxxflags` -Wno-deprecated-declarations
RESINC = 
LIBDIR = 
LIB = -lGL -lavcodec -lavformat -lavutil -lswscale
LDFLAGS = `wx-config  --libs std gl`

INC_DEBUG = $(INC)
CFLAGS_DEBUG = $(CFLAGS) -g
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = bin/Debug/StreamPlayer

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -O2
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE =  -s $(LDFLAGS)
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = bin/Release/StreamPlayer

OBJ_DEBUG = $(OBJDIR_DEBUG)/StreamPlayerApp.o $(OBJDIR_DEBUG)/StreamPlayerMain.o $(OBJDIR_DEBUG)/StreamReceiver.o $(OBJDIR_DEBUG)/VideoGLCanvas.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/StreamPlayerApp.o $(OBJDIR_RELEASE)/StreamPlayerMain.o $(OBJDIR_RELEASE)/StreamReceiver.o $(OBJDIR_RELEASE)/VideoGLCanvas.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG) || mkdir -p $(OBJDIR_DEBUG)

after_debug: 
	cp -r ./res ./bin/Debug

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/StreamPlayerApp.o: StreamPlayerApp.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c StreamPlayerApp.cpp -o $(OBJDIR_DEBUG)/StreamPlayerApp.o

$(OBJDIR_DEBUG)/StreamPlayerMain.o: StreamPlayerMain.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c StreamPlayerMain.cpp -o $(OBJDIR_DEBUG)/StreamPlayerMain.o

$(OBJDIR_DEBUG)/StreamReceiver.o: StreamReceiver.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c StreamReceiver.cpp -o $(OBJDIR_DEBUG)/StreamReceiver.o

$(OBJDIR_DEBUG)/VideoGLCanvas.o: VideoGLCanvas.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c VideoGLCanvas.cpp -o $(OBJDIR_DEBUG)/VideoGLCanvas.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)

before_release: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE) || mkdir -p $(OBJDIR_RELEASE)

after_release: 
	cp -r ./res ./bin/Release

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/StreamPlayerApp.o: StreamPlayerApp.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c StreamPlayerApp.cpp -o $(OBJDIR_RELEASE)/StreamPlayerApp.o

$(OBJDIR_RELEASE)/StreamPlayerMain.o: StreamPlayerMain.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c StreamPlayerMain.cpp -o $(OBJDIR_RELEASE)/StreamPlayerMain.o

$(OBJDIR_RELEASE)/StreamReceiver.o: StreamReceiver.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c StreamReceiver.cpp -o $(OBJDIR_RELEASE)/StreamReceiver.o

$(OBJDIR_RELEASE)/VideoGLCanvas.o: VideoGLCanvas.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c VideoGLCanvas.cpp -o $(OBJDIR_RELEASE)/VideoGLCanvas.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

